### ISSUE TITLE
Error when Function Define 

### ISSUE THREAD

**Issue by WithSJ** [CsqLang/Csq3#10]
**This code works and give output correctly** 
```
def fizz(){
    return str("Hello World")
}

print(fizz())
```

**but when I put Curley braces in the new line** 
```
def fizz()
{
    return str("Hello World")
}

print(fizz())
```

**it gives me an error**
```
/home/jadam/Desktop/GITHUB/hello.cpp:3:1: error: expected unqualified-id before ‘{’ token
    3 | {;
      | ^
/home/jadam/Desktop/GITHUB/hello.cpp: In function ‘int main()’:
/home/jadam/Desktop/GITHUB/hello.cpp:8:11: error: use of ‘auto fizz()’ before deduction of ‘auto’
    8 | print(fizz());
      |       ~~~~^~
sh: 1: ./hello: not found
jadam@jadam-pc:~/Desktop/GITH
```

**IN hello.cpp File semi-colen at the end of def fizz()**
I think problem is here
```

#include "/home/jadam/Desktop/GITHUB/Csq3/Modules/builtins.csqm"
def fizz();
{;
    return str("Hello World");
};

int main(){
print(fizz());
return 0;}

```

**Comment by AniketKumar2500** [comment]
Hello,
Yes this is a rule to define functions in such a way that they doesn't have curly brace in a new line so hence it's not an error it's defined by syntax.

**Comment by AniketKumar2500** [comment]
but if you want to define with curly brace in new line so write like this:
meth fizz=[](){
   return str("Hello World")
};

**Comment by AniketKumar2500** [comment]
Semicolan are the main issue as after every end of line it puts semicolan.

**Comment by WithSJ** [comment]
ok... it's syntax.
but if it's syntax so  this code should be work 
it give me another error
```
def fizz(){return str("Hello World")}

print(fizz())

```

**now in hello.cpp it not create main()**
```

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
sh: 1: ./hello: not found
```

**Comment by AniketKumar2500** [comment]
Its because the parser thinks that the end is not at the same line.
