### ISSUE TITLE
Println not working with one argument

### ISSUE THREAD

**Issue by AniketKumar2500** [CsqLang/Csq3#20]
When using println with more than one argument it works but with a single one it's like:
![err](https://user-images.githubusercontent.com/90708238/208362252-895303c2-8ad6-44a6-b794-fdc4d8b3d88b.png)
Output shall be:
0
1
2
3
4
5
6
7
8
9

**Comment by AniketKumar2500** [comment]
This is the code for the bug in Modules/headers/comb.h : 
![bog](https://user-images.githubusercontent.com/90708238/208362775-93803b2d-0bb6-4427-a89d-1f781b815624.png)

**Comment by gvanrossum** [comment]
The first template doesn't have `\n` at the end of the format string, it should be
```
    printf("%s\n", tostr(t).Str);
```

PS. Please copy-paste text instead of images.

**Comment by AniketKumar2500** [comment]
Thanks for the solution sir! :)
