### ISSUE TITLE
println not working properly

### ISSUE THREAD

**Issue by WithSJ** [CsqLang/Csq3#8]
**when I write code**

```
for var i : range(5) so 
println("Hello world ", 100," | ",200)
ends

```

**Output**

Hello world 
100 | 200Hello world 
100 | 200Hello world 
100 | 200Hello world 
100 | 200Hello world 
100 | 200

**The output should be like this** 
Hello world 100 | 200
Hello world 100 | 200
Hello world 100 | 200
Hello world 100 | 200
Hello world 100 | 200

it put \n after first arg "Hello world"

**Comment by AniketKumar2500** [comment]
Hi,
The output should be :
Hello world
100
 | 
200

As after every args it puts \n.

**Comment by AniketKumar2500** [comment]
For the purpose you made you should use print not println because print just print where println prints and adds a new line after every arg.

**Comment by AniketKumar2500** [comment]
Thanks to point it out

**Comment by AniketKumar2500** [comment]
Nice idea👍👍

**Comment by WithSJ** [comment]
> Nice idea👍👍

I already fixed it... Check pull request
